Models/City.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreTagHelpersExamples.Models
{
    public class City
    {
        [Display(Name="City")]
        public string Name { get; set; }
        public string Country { get; set; }

        [DisplayFormat(DataFormatString = "{0:F2}", ApplyFormatInEditMode = true)]
        public int? Population { get; set; }

        public string Notes { get; set; }
    }
}

Models/CountryNames.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreTagHelpersExamples.Models
{
    public enum CountryNames
    {
        UK, USA,France,China
    }
}

Models/IRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreTagHelpersExamples.Models
{
    public interface IRepository
    {
        IEnumerable<City> Cites { get; }
        void AddCity(City newCity);
    }
}

Models/MemoryRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreTagHelpersExamples.Models
{
    public class MemoryRepository : IRepository
    {
        private List<City> cities = new List<City>
        {
            new City {Name="London",Country="UK", Population=8539000 },
            new City {Name="New York",Country="USA", Population=8406000 },
            new City {Name="San Jose",Country="USA", Population=998537 },
            new City {Name="Paris", Country="France", Population=2244000 }
        };
        public IEnumerable<City> Cites
        {
            get
            {
                return cities;
            }
        }

        public void AddCity(City newCity)
        {
            cities.Add(newCity);
        }
    }
}

Components/TimeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreTagHelpersExamples.Components
{
    public class TimeViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View(DateTime.Now);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreTagHelpersExamples.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AspNetCoreTagHelpersExamples.Controllers
{
    public class HomeController : Controller
    {
        private IRepository repository;

        public HomeController(IRepository repo)
        {
            repository = repo;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(repository.Cites);
        }

        public ViewResult Edit() {
            ViewBag.Countries = new SelectList(repository.Cites.Select(c => c.Country).Distinct());
           return  View("Create", repository.Cites.First());
        }

        public ViewResult Create()
        {
            ViewBag.Countries = new SelectList(repository.Cites.Select(c => c.Country).Distinct());
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(City city)
        {
            repository.AddCity(city);
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Components/Time/Default.cshtml
@model DateTime

<div class="panel-body bg-info">
    Rendered at @Model.ToString("HH:mm:ss")
</div>

Views/Home/Create.cshtml
@model City
@addTagHelper AspNetCoreTagHelpersExamples.Infrastructure.TagHelpers.*, AspNetCoreTagHelpersExamples

@{ Layout = "_Layout";}

<form method="post" asp-controller="Home" asp-action="Create" asp-antiforgery="true">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" asp-for="Name" />
    </div>
    @*<div class="form-group">
        <label asp-for="Country">Country</label>
        <input class="form-control" asp-for="Country" />
    </div>*@

    @*<div class="form-group">
        <label asp-for="Country"></label>
        <select class="form-control" asp-for="Country">
            <option disabled selected value="">Select a Country</option>
            <option>UK</option>
            <option>USA</option>
            <option>France</option>
            <option>China</option>
        </select>
    </div>*@

    @*<div class="form-group">
        <label asp-for="Country"></label>
        <select class="form-control" asp-for="Country" asp-items="@new SelectList(Enum.GetNames(typeof(CountryNames)))">
            <option disabled selected value="">Select a Country</option>
        </select>
    </div>*@

    <div class="form-group">
        <label asp-for="Country"></label>
        <select class="form-control" asp-for="Country" asp-items="ViewBag.Countries">
            <option disabled selected value="">Select a Country</option>
        </select>
    </div>
    
    <div class="form-group">
        <label asp-for="Population">Population</label>
        <input class="form-control" asp-for="Population"  />
    </div>

    @*<button type="submit" bs-button-color="danger">Add</button>
    <button type="reset" class="btn btn-primary">Reset</button>*@
    @*<div theme="primary">
        <formbutton type="submit" bg-color="danger" />
        <formbutton type="reset" />
        <a bs-button-color="primary" href="/Home/Index">Cancel</a>
    </div>*@

    <div class="form-group">
        <label asp-for="Notes"></label>
        <textarea class="form-control" asp-for="Notes"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Add</button>
    <a class="btn btn-primary" href="/Home/Index">Cancel</a>
</form>

Views/Home/Index.cshtml
@model IEnumerable<City>

@{ 
    Layout = "_Layout";
}

<table class="table table-condensed table-bordered">
    <thead class="bg-primary">
        <tr>
            <th>Name</th>
            <th>Country</th>
            <th class="text-right">Population</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var city in Model)
        {
            <tr>
                <td wrap>@city.Name</td>
                <td>@city.Country</td>
                <td class="text-right">@city.Population?.ToString()</td>
            </tr>

        }
    </tbody>
</table>

<a asp-action="Create" class="btn btn-primary">Create</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cites</title>
    <script asp-src-include="lib/jquery/dist/**/*.js" asp-src-exclude="**.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js"
            asp-fallback-src-include="/lib/jquery/dist/**/*.min.js"
            asp-fallback-test="window.jQuery"></script>
    <link asp-href-include="/lib/bootstrap/dist/**/.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          asp-fallback-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-fallback-test-class="btn"
          asp-fallback-test-property="display"
          asp-fallback-test-value="inline-block" rel="stylesheet" />
</head>
<body class="panel-body">
    @*<div show-for="Index" class="panel-body bg-danger">
        <h2>Important Message</h2>
    </div>*@
    <environment names="development">
        <div class="panel-body bg-info"><h2>This is Development</h2></div>
    </environment>
    <environment names="production">
        <div class="panel-body bg-danger"><h2>This is Production</h2></div>
    </environment>
    <img src="~/images/city.jpg" asp-append-version="true" />
    <cache expires-after="@TimeSpan.FromSeconds(15)" vary-by-route="action">
        @await Component.InvokeAsync("Time")
    </cache>
    <div>
        @RenderBody()
    </div>
</body>
</html>